GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnVkaSIsImlhdCI6MTU5NzI4MzcwM30.VSBACaUdtyK7Eyjn1jxelc0gtcKI-4df8Oq_NKqwsaE

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Budi"
}